language: generic
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
os:
- linux
env:
  matrix:
  - CLI_VERSION=Latest
matrix:
  allow_failures:
  - env: CLI_VERSION=Latest
before_install:
- curl -L --create-dirs https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh
  -o ./scripts/obtain/install.sh
- find ./scripts -name "*.sh" -exec chmod +x {} \;
- export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
- sudo bash ./scripts/obtain/install.sh --channel "preview" --version "$CLI_VERSION"
  --install-dir "$DOTNET_INSTALL_DIR" --no-path
- export PATH="$DOTNET_INSTALL_DIR:$PATH"
- chmod +x ./build.sh
script:
- "./build.sh"
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: FoTmAMvqsU8QZorp7trAfdZQg59mW7RHrOgXz19Rgxp41uroilsSfKPPD1lNH/Hcx2+n2jpf1ekFHrzE0rSd/ahj6aienaHPr34vM7Ky0PyiquPG7VOQnrSn+eVnWK6yEbE5MvZX0fqYX0HeuCXNoI19j2H9dMCwCcxxnguLKOxoQfJxelmPMONtxca5sNA9JrToRTaoTDnp0VB3vW/NMlAyaAuzWOAY1SbCOL694gmIfExs+CRS7S3lJCP27AvQieEa7HOALdnyto+cbo8Xtb5Ot4dWQo0jVAaaazz4+dfUQ+GtmU0gvN6VzlHG1FCiAkJlQ6SibVTCO+09lP05XM+NWfxBWpCMCmHNl7+bneVo2LkuMZQ7F5junlDzxckPewl+pRYIFh7wwBlrcj1jHu4LG9UYTMmTcLuK0iwrcjzTi8BJID1n4j4ciZa1fzVy585gTqgTRNUAwBVCj2RawCLw6MUMmdIAJcLrhhYfRi8N+J2+iNcnRDDnN9tTb5S3WiPpsM7TgS5MkoY5RV1KayEZ7dYdXHKie9oa0FhnRgYFH6K9CW3MlDEYf1peneSlw9xc8JLa6GIdAf+EWwYlfflIUR1JdKUr8izMt1qT1KWbOiN1KjDJtQSmofDGSUBf+RozNasIhxMaN/XtuzqohOqvI2asM7HZZCmgHLHcrD4=
  app:
    heroku: nge-dev
  run: '"cd ~/heroku_output/Nge.Web && dotnet ef database update"'