language: generic
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
os:
- linux
env:
  matrix:
  - CLI_VERSION=Latest
matrix:
  allow_failures:
  - env: CLI_VERSION=Latest
before_install:
- curl -L --create-dirs https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh
  -o ./scripts/obtain/install.sh
- find ./scripts -name "*.sh" -exec chmod +x {} \;
- export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
- sudo bash ./scripts/obtain/install.sh --channel "preview" --version "$CLI_VERSION"
  --install-dir "$DOTNET_INSTALL_DIR" --no-path
- export PATH="$DOTNET_INSTALL_DIR:$PATH"
- chmod +x ./build.sh
script:
- "./build.sh"
